### ISSUE TITLE
CORDEX-CMIP6 in the ACCESS-NRI ESMValTool setup

### ISSUE THREAD

**Issue by EmmaHoward** [ACCESS-NRI/CMIP7-Hackathon#35]
Hi, 

Following conversations at the September hackathon, I've had successfully loaded the Australian CORDEX-CMIP6 data and the BARRA2 reanalysis data into your ESMValTool workflow. Are you able to include these changes into your workflow so that we can jointly develop recipes for regional and global models and assess against BARRA2? 

I've been able to test my setup with the warming stripes example you provided in the September hackathon. My version successfully runs in the command line with a local copy of ESMValCore at /scratch/nf33/eh6215/CMIP7-Hackathon/exercises/AdvancedJupyterNotebook/esmvalcore, however it would be much better if they were included in your officially supported version. I haven't worked out how to use my updated config-developer file in Jupyter sessions, and it would also be great if this functionality could be available to other users. 

Please let me know if you'd like to talk more about this.

Best wishes, 
Emma

1) Edit config-developer and config-user to include the following entries:

**config-developer.yml**
```
CORDEX-CMIP6:                                                                                                                  
  input_dir:                                                                                                             
    default: '/'                                                                                                         
    NCI: 'CMIP6/DD/{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}/{version}'
  input_file: '{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}_{dataset}_{rcm_version}_{mip}*.nc'
  output_file: '{project}_{dataset}_{rcm_version}_{driver}_{domain}_{mip}_{exp}_{ensemble}_{short_name}'                 
  cmor_type: 'CMIP6'
  cmor_path: '/scratch/nf33/eh6215/CMIP7-Hackathon/exercises/AdvancedJupyterNotebook/esmvalcore/cmor/tables/cordex-cmip6'
                                                                                                                          
BARRA2:
  input_dir:
    default: '/'
    NCI: 'reanalysis/{domain}/{institute}/{driver}/{exp}/{ensemble}/{dataset}/{rcm_version}/{mip}/{short_name}/{version}'
  input_file: '{short_name}_{domain}_{driver}_{exp}_{ensemble}_{institute}_{dataset}_{rcm_version}_{mip}*.nc'
  output_file: '{project}_{dataset}_{rcm_version}_{driver}_{domain}_{mip}_{exp}_{ensemble}_{short_name}'
  cmor_type: 'CMIP6'
  cmor_path: '/scratch/nf33/eh6215/CMIP7-Hackathon/exercises/AdvancedJupyterNotebook/esmvalcore/cmor/tables/cordex-cmip6'
```
    
**config-user.yml**
```
rootpath
    CORDEX-CMIP6: 
      - /g/data/hq89/CCAM/output/
      - /g/data/py18/BARPA/output/
      - /g/data/zz63/NARCliM2-0/output/
      - /g/data/ig45/QldFCP-2/output/
    BARRA2: 
      - /g/data/ob53/BARRA2/output
    
drs
  CORDEX-CMIP6: NCI
  BARRA2: NCI    
```

2) Add CMOR tables from https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables. 

I added these locally on scratch, however they should ideally be installed at:
        /opt/conda/esmvaltool-0.4/lib/python3.11/site-packages/esmvalcore
   "cmor_paths" in config_developer should be edited to match this too. I think a local path will do when the tables are put in the right place.
   Edit the headers in the downloaded frequency cmor tables (1hr, 6hr, day, fx, mon) to include the entry `"generic_levels": ""`. This is something ESMValTool looks for but cannot find due to a difference between CORDEX and CMIP6. 

3) To test with the warming stripes recipe provided in the hackathon, I had to replace the dataset loader with following in the yaml recipe file.

**For BARRA2:**
```
datasets:
  - dataset: BARRA-R2
    project: BARRA2
    mip: mon
    exp: historical
    driver: ERA5
    ensemble: hres
    start_year: 1980
    end_year: 2020
    rcm_version: v1
    domain: AUS-11
    institute: BOM
    supplementary_variables:
       - short_name: areacella
         mip: fx
         skip: True
```
    
**For CORDEX (only tested with one BARPA simulation):**
```
datasets:
  - dataset: BARPA-R
    project: CORDEX-CMIP6
    mip: mon
    exp: historical
    driver: ACCESS-ESM1-5
    ensemble: r6i1p1f1
    start_year: 1960
    end_year: 2014
    rcm_version: v1-r1
    domain: AUS-15
    institute: BOM
    supplementary_variables:
       - short_name: areacella
         mip: fx
         skip: True 
```
